# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "http://localhost:4321"

[_.globalMeta]
title = "Thomas Brandoli"
description = "Software, game development, audio & things I'm building."
longDescription = "A personal blog and portfolio about software development, game development, audio programming, projects, and things I find interesting."
cardImage = "https://zaggonaut.dev/michael-dam-unsplash.webp"
keywords = ["software development", "game development", "audio programming", "c++", "unreal engine", "godot"]

[_.blogMeta]
title = "Blog"
description = "Thoughts, experiments, tutorials, and things I've learned."
longDescription = "Articles about software development, game development, audio programming, tools and experiments."
cardImage = "https://zaggonaut.dev/michael-dam-unsplash.webp"
keywords = ["software development", "game development", "audio programming", "c++", "unreal engine", "godot", "thoughts"]

[_.projectMeta]
title = "Projects"
description = "Things I've built, broken, fixed, and shipped."
longDescription = "A collection of personal projects."
cardImage = "https://zaggonaut.dev/michael-dam-unsplash.webp"
keywords = ["projects", "game development", "software development", "c++", "unreal engine", "godot"]

[_.notFoundMeta]
title = "404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "https://zaggonaut.dev/michael-dam-unsplash.webp"

[_.hero]
title = "Thomas Brandoli"
subtitle = "Code, Games & Sound"
image = "https://zaggonaut.dev/michael-dam-unsplash.webp"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "Thomas Brandoli"
githubProfile = "https://github.com/ThGnommy"
itchProfile = "https://gnommy.itch.io/"
linkedinProfile = "https://www.linkedin.com/in/thbrandoli"

[_.texts]
articlesName = "Articles"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
blog = "/blog"
